// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU7puYBqEpGWC9r5xpdnqsS5p6WXbhz2k',
    appId: '1:576274387112:web:ad6b06d416fa969724729d',
    messagingSenderId: '576274387112',
    projectId: 'canteen-77794',
    authDomain: 'canteen-77794.firebaseapp.com',
    storageBucket: 'canteen-77794.appspot.com',
    measurementId: 'G-TGR7MPVQEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcx11Kh0OECxFiWgZZw7Yq3upzIoiXV5U',
    appId: '1:576274387112:android:8579ced27876a4f224729d',
    messagingSenderId: '576274387112',
    projectId: 'canteen-77794',
    storageBucket: 'canteen-77794.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzqVlTFZTTOCOXLj5iMCigZBXgtCSGUrA',
    appId: '1:576274387112:ios:292897a7d540961724729d',
    messagingSenderId: '576274387112',
    projectId: 'canteen-77794',
    storageBucket: 'canteen-77794.appspot.com',
    iosBundleId: 'com.example.canteeno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzqVlTFZTTOCOXLj5iMCigZBXgtCSGUrA',
    appId: '1:576274387112:ios:292897a7d540961724729d',
    messagingSenderId: '576274387112',
    projectId: 'canteen-77794',
    storageBucket: 'canteen-77794.appspot.com',
    iosBundleId: 'com.example.canteeno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU7puYBqEpGWC9r5xpdnqsS5p6WXbhz2k',
    appId: '1:576274387112:web:1de2f56605e0b8d424729d',
    messagingSenderId: '576274387112',
    projectId: 'canteen-77794',
    authDomain: 'canteen-77794.firebaseapp.com',
    storageBucket: 'canteen-77794.appspot.com',
    measurementId: 'G-0ETNKMVZ9J',
  );
}
